# Generated by Django 6.0.8 on 2026-08-29 22:26

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extras', '0140_imageattachment_image_size'),
        ('tenancy', '0024_default_ordering_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=200)),
                ('vcn', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oci_security_lists', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'OCI 보안목록',
                'verbose_name_plural': 'OCI 보안목록',
                'ordering': ('tenant', 'vcn', 'name'),
                'unique_together': {('tenant', 'vcn', 'name')},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SecurityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('direction', models.CharField(max_length=10)),
                ('protocol', models.CharField(max_length=10)),
                ('ports', models.CharField(blank=True, max_length=50)),
                ('peer', models.CharField(max_length=100)),
                ('stateless', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('security_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='netbox_oci.securitylist')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'OCI 보안규칙',
                'verbose_name_plural': 'OCI 보안규칙',
                'ordering': ('security_list', 'direction', 'protocol', 'ports'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
